CREATE TABLE people (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL UNIQUE,
    account BOOLEAN,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    username TEXT UNIQUE,
    password TEXT
);

CREATE TABLE schedules (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    people_id INTEGER REFERENCES people(id),
    schedule_name TEXT NOT NULL,
    status TEXT,
    responses INTEGER NOT NULL DEFAULT 0,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    meeting_duration TEXT NOT NULL
);

CREATE TABLE roles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    schedule_id INTEGER REFERENCES schedules(id),
    role_name TEXT NOT NULL
);

CREATE TABLE timeslots (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    schedule_id INTEGER REFERENCES schedules(id),
    timeslot TEXT NOT NULL,
    day_name TEXT NOT NULL
);

CREATE TABLE avail (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    schedule_id INTEGER REFERENCES schedules(id),
    timeslot INTEGER REFERENCES timeslots(id),
    people_id INTEGER REFERENCES people(id),
    role_name TEXT NOT NULL
);