CREATE TABLE complete (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    schedule_id INTEGER REFERENCES schedules(id),
    people_name TEXT NOT NULL,
    role_name TEXT NOT NULL,
    timeslot INTEGER REFERENCES timeslots(id)
);